### ISSUE TITLE
i.MX6: EGL有効化時に高負荷をかけるとフリーズすることがある

### ISSUE THREAD

**Issue by ashie** [mozilla-japan/gecko-embedded#7]
i.MX6でEGLを有効化すると、Canvas等で負荷をかけたときに稀に画面がフリーズすることがある。
現象再現時のcoreを取れたのでスタックトレースを貼り付けておく。

```
#0  0x76d2f2c0 in poll () at ../sysdeps/unix/syscall-template.S:81                                                [36/1868]
#1  0x712a8d54 in _xcb_conn_wait (c=c@entry=0x76a9f000, cond=cond@entry=0x76aa00e8, vector=vector@entry=0x7ef87bbc, 
    count=count@entry=0x7ef87bb8) at /usr/src/debug/libxcb/1.11-r0/libxcb-1.11/src/xcb_conn.c:459
#2  0x712a93f0 in _xcb_out_send (c=c@entry=0x76a9f000, vector=vector@entry=0x7ef87c10, count=count@entry=3)
    at /usr/src/debug/libxcb/1.11-r0/libxcb-1.11/src/xcb_out.c:393
#3  0x712a9484 in xcb_writev (c=c@entry=0x76a9f000, vector=vector@entry=0x7ef87c10, count=count@entry=3, 
    requests=requests@entry=127) at /usr/src/debug/libxcb/1.11-r0/libxcb-1.11/src/xcb_out.c:341
#4  0x7368869c in _XSend (dpy=0x76a9e000, data=0x0, size=<optimized out>)
    at /usr/src/debug/libx11/1_1.6.2-r0/libX11-1.6.2/src/xcb_io.c:495
#5  0x73688b7c in _XReply (dpy=dpy@entry=0x76a9e000, rep=rep@entry=0x7ef87c90, extra=2130214032, extra@entry=0, 
    discard=1937125988, discard@entry=1) at /usr/src/debug/libx11/1_1.6.2-r0/libX11-1.6.2/src/xcb_io.c:581
#6  0x73684a1c in XSync (dpy=0x76a9e000, discard=discard@entry=0)
    at /usr/src/debug/libx11/1_1.6.2-r0/libX11-1.6.2/src/Sync.c:44
#7  0x7381c830 in sync (display=0x6709c000, display=0x6709c000)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-xlib-surface-shm.c:461
#8  _cairo_xlib_surface_update_shm (surface=surface@entry=0x679db800)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-xlib-surface-shm.c:952
#9  0x7381d3d0 in _cairo_xlib_surface_get_shm (surface=surface@entry=0x679db800, overwrite=overwrite@entry=0)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-xlib-surface-shm.c:1045
#10 0x7381aa28 in _cairo_xlib_surface_acquire_source_image (abstract_surface=0x679db800, image_out=0x7ef88df0, 
    image_extra=<optimized out>) at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-xlib-surface.c:1394
#11 0x737eeaa8 in _cairo_surface_acquire_source_image (surface=0x679db800, image_out=<optimized out>, 
    image_extra=<optimized out>) at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-surface.c:1887
#12 0x737bc6b8 in _pixman_image_for_surface (iy=0x7ef88ef8, ix=0x7ef88ef4, sample=0x7ef895b4, extents=0x7ef89590, 
    is_mask=1352131440, pattern=0x7ef895d8, dst=0x679db800)
#13 _pixman_image_for_pattern (dst=dst@entry=0x5097e370, pattern=pattern@entry=0x7ef895d8, is_mask=is_mask@entry=0,[9/1868]
    extents=extents@entry=0x7ef89590, sample=sample@entry=0x7ef895b4, tx=tx@entry=0x7ef88ef4, ty=ty@entry=0x7ef88ef8)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-image-source.c:1124
#14 0x737bcecc in _cairo_image_source_create_for_pattern (dst=0x5097e370, pattern=0x7ef895d8, is_mask=0, 
    extents=0x7ef89590, sample=0x7ef895b4, src_x=0x7ef88ef4, src_y=0x7ef88ef8)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-image-source.c:1169
#15 0x737eb714 in composite_aligned_boxes (boxes=0x7ef89300, extents=0x7ef89558, compositor=0x73878034 <spans>)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-spans-compositor.c:669
#16 clip_and_composite_boxes (compositor=compositor@entry=0x73878034 <spans>, extents=extents@entry=0x7ef89558, 
    boxes=boxes@entry=0x7ef89300) at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-spans-compositor.c:873
#17 0x737ebcd0 in clip_and_composite_boxes (compositor=0x73878034 <spans>, extents=0x7ef89558, boxes=0x7ef89300)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-spans-compositor.c:892
#18 0x737ebd8c in _cairo_spans_compositor_paint (_compositor=0x73878034 <spans>, extents=0x7ef89558)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-spans-compositor.c:974
#19 0x737ae048 in _cairo_compositor_paint (compositor=0x73878034 <spans>, surface=0x5097e370, op=<optimized out>, 
    source=<optimized out>, clip=0x0) at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-compositor.c:65
#20 0x737bd060 in _cairo_image_surface_paint (abstract_surface=<optimized out>, op=<optimized out>, 
    source=<optimized out>, clip=<optimized out>)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-image-surface.c:924
#21 0x737eec98 in _cairo_surface_paint (surface=0x5097e370, op=CAIRO_OPERATOR_OVER, source=0x7ef89838, clip=0x0)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-surface.c:2031
#22 0x737b4f84 in _cairo_gstate_paint (gstate=0x58d87020)
    at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo-gstate.c:1067
#23 0x737a8e24 in INT_cairo_paint (cr=0x58d87000) at /usr/src/debug/cairo/1.12.18-r0/cairo-1.12.18/src/cairo.c:1999
#24 0x74673d0c in mozilla::gfx::SourceSurfaceCairo::GetDataSurface() ()
   from /opt/fsl-imx-x11/3.14.52-1.1.0/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi/usr/lib/firefox-45.2.0/libxul.so
#25 0x746e29c4 in mozilla::layers::BasicLayerManager::PaintLayer(gfxContext*, mozilla::layers::Layer*, void (*)(mozilla::la
```

**Comment by ashie** [comment]
この問題はバックエンドをskiaに変えると発生しない。

user.js
```
user_pref("gfx.canvas.azure.backends", "skia");
user_pref("gfx.content.azure.backends", "skia");
```

ただし、skiaではフォント描画等が乱れる。

**Comment by ashie** [comment]
Firefox 45 では以下のGUIMark3やStarWarsを行き来していると確実に発生していたが、  #13 のFirefox 50 では今のところ再現していない。

  * [GUIMark3 HTML5 Bitmap](http://www.craftymind.com/factory/guimark3/bitmap/GM3_JS_Bitmap.html)
  * [GUIMark3 Vector](http://www.craftymind.com/factory/guimark3/vector/GM3_JS_Vector.html)
  * [GUIMark3 Compute (Canvas)](http://www.craftymind.com/factory/guimark3/compute/GM3_JS_Compute.html)
  * [Star Wars: The Force Awakens in CSS](http://codepen.io/donovanh/full/pJzwEw/)
